# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: All Things Serve The Code
email: ryan.norman@servethecode.com
description: > # this means to ignore newlines until "baseurl:"
  Herding Catz AKA learning how to be technical lead on a team full of developers smarter than me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://servethecode.com" # the base hostname & protocol for your site
twitter_username: rsnorman
github_username:  rsnorman
google_analytics: UA-43183791-6

# Build settings
markdown: kramdown
